# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            鈴木商店
tagline:          'A Jekyll theme'
description:      'The <a href="http://hyde.getpoole.com" target="_blank">Hyde</a> theme for <a href="http://jekyllrb.com" target="_blank">Jekyll</a>, refreshed.'
url:              https://suzukishouten.github.io/web-development-tutorial/

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            1.0.0
sidebar_home_link:  true

github:
  repo:             https://github.com/suzukiSHOUTEN/web-development-tutorial
